b1 = input("Put in a birthday ")
b2 = input("Put in a birthday ")
b3 = input("Put in a birthday ")
b4 = input("Put in a birthday ")
b5 = input("Put in a birthday ")
print("Ok so your 5 birthdays are", b1 , b2 , b3 , b4 , b5)